name: dart_qjson
description: Immutable Qt-style JSON object and list wrappers for Dart, providing type-safe access and smart casting via Variant
version: 1.0.2

repository: https://github.com/Auramel/dart_qjson

environment:
  sdk: ^3.8.1

dependencies:
  dart_qvariant: ^1.0.2

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^6.0.0
  test: ^1.24.0
